### ISSUE TITLE
TypeError: unhashable type: 'collections.OrderedDict'

### ISSUE THREAD

**Issue by Mi-Al** [mschwager/gitem#10]
Hello, when I launch the program like this:

`gitem repository Mi-Al WiFi-autopwner`

I got the error:

```
Traceback (most recent call last):
  File "/usr/bin/gitem", line 11, in <module>
    load_entry_point('gitem==0.8.1', 'console_scripts', 'gitem')()
  File "/usr/lib/python3.8/site-packages/gitem/__main__.py", line 285, in main
    dispatch[args.command](ghapi, outputter, **vars(args))
  File "/usr/lib/python3.8/site-packages/gitem/__main__.py", line 109, in repository
    ("Contributors", collections.OrderedDict([
TypeError: unhashable type: 'collections.OrderedDict'
```

I run it on Arch Linux.

**Comment by mschwager** [comment]
Hey, thanks for reporting this! I fixed the issue in the above commit, and will release a fixed version soon :+1:

**Comment by mschwager** [comment]
The latest version on PyPI (upgrade with `pip install -U gitem`) has the fix - thanks again!
